### PR TITLE
Add PHP8 support

### PR DESCRIPTION
**Pull request by boboldehampsink**

### CODE REVIEW

**Comment by sebastian-lenz** [comment]
Thanks @boboldehampsink!

**Comment by boboldehampsink** [comment]
@sebastian-lenz welcome :-) any plans on a release?

**Comment by jon14four** [comment]
@sebastian-lenz Also interested since craft 5.6 now supports 8

**Comment by devotoare** [comment]
@sebastian-lenz  Also interested since craft 5.6 now supports 8

**Comment by sebastian-lenz** [comment]
This pull requests targets v1 which I've published last week. For v2 I am still looking into two other issues before releasing a new version.

**Pull request merged**
